export const colorsPalette = {
    light: {
        colorsBackground: '#ffffff',
        colorsSidebarBackground: '#ffffff',
        colorsMainBackground: '#ffffff',
        colorsBorder: '#ffc2c2',
        colorsText: '#2d2d2d',
        colorsTitle: 'var(--globalColorPrimaryInmutable)',
        colorsSubtitle: '#666666',
        colorsTableHeader: '#f8f9fa',
        colorsTableBorder: '#dee2e6',
        colorsButtonPrimary: 'var(--globalColorPrimaryInmutable)',
        colorsButtonPrimaryHover: 'var(--globalColorAccent)',
        colorsButtonText: '#ffffff',
        colorsCardBackground: 'var(--globalColorCardBackground)',
        colorsCardBorder: 'var(--globalColorCardBorderLight)',
        colorsCardBorderHover: 'var(--globalColorCardBorderHover)',
        colorsCardText: 'var(--globalColorTextDark)',
        colorsFormBackground: '#ffffff',
        colorsFormInput: '#ffffff',
        colorsFormInputText: '#333333',
        colorsFormInputBorder: '#ddd'
    },
    dark: {
        colorsBackground: '#2c2c2c',
        colorsSidebarBackground: '#2f2f2f',
        colorsMainBackground: '#2f2f2f',
        colorsBorder: '#ff6d6dc4',
        colorsText: '#ffffff',
        colorsTitle: 'var(--globalColorTitle)',
        colorsSubtitle: '#a1a1a1',
        colorsTableHeader: '#1f1f1f',
        colorsTableBorder: '#414141',
        colorsButtonPrimary: 'var(--globalColorMainBackgroundStart)',
        colorsButtonPrimaryHover: 'var(--globalColorMainBackgroundEnd)',
        colorsButtonText: '#ffffff',
        colorsCardBackground: 'var(--globalColorCardBackground)',
        colorsCardBorder: 'var(--globalColorCardBorderLight)',
        colorsCardBorderHover: 'var(--globalColorCardBorderHover)',
        colorsCardText: 'var(--globalColorTextLight)',
        colorsFormBackground: '#333333',
        colorsFormInput: '#444444',
        colorsFormInputText: '#ffffff',
        colorsFormInputBorder: '#555555'
    }
}; 