export const reportsPalette = {
    light: {
        reportsBackground: '#ffffff',
        reportsSidebarBackground: '#ffffff',
        reportsMainBackground: '#ffffff',
        reportsBorder: '#ffc2c2',
        reportsText: '#2d2d2d',
        reportsTitle: 'var(--globalColorPrimaryInmutable)',
        reportsSubtitle: '#666666',
        reportsTableHeader: '#f8f9fa',
        reportsTableBorder: '#dee2e6',
        reportsButtonPrimary: 'var(--globalColorPrimaryInmutable)',
        reportsButtonPrimaryHover: 'var(--globalColorAccent)',
        reportsButtonText: '#ffffff',
        reportsCardBackground: 'var(--globalColorCardBackground)',
        reportsCardBorder: 'var(--globalColorCardBorderLight)',
        reportsCardBorderHover: 'var(--globalColorCardBorderHover)',
        reportsCardText: 'var(--globalColorTextDark)',
        reportsFormBackground: '#ffffff',
        reportsFormInput: '#ffffff',
        reportsFormInputText: '#333333',
        reportsFormInputBorder: '#ddd'
    },
    dark: {
        reportsBackground: '#2c2c2c',
        reportsSidebarBackground: '#2f2f2f',
        reportsMainBackground: '#2f2f2f',
        reportsBorder: '#ff6d6dc4',
        reportsText: '#ffffff',
        reportsTitle: 'var(--globalColorTitle)',
        reportsSubtitle: '#a1a1a1',
        reportsTableHeader: '#1f1f1f',
        reportsTableBorder: '#414141',
        reportsButtonPrimary: 'var(--globalColorMainBackgroundStart)',
        reportsButtonPrimaryHover: 'var(--globalColorMainBackgroundEnd)',
        reportsButtonText: '#ffffff',
        reportsCardBackground: 'var(--globalColorCardBackground)',
        reportsCardBorder: 'var(--globalColorCardBorderLight)',
        reportsCardBorderHover: 'var(--globalColorCardBorderHover)',
        reportsCardText: 'var(--globalColorTextLight)',
        reportsFormBackground: '#333333',
        reportsFormInput: '#444444',
        reportsFormInputText: '#ffffff',
        reportsFormInputBorder: '#555555'
    }
}; 