export const managementPalette = {

    light: {

        managementColorBackgroundUser:'rgb(255, 255, 255)',
        managementColorTextUser:'rgb(82, 82, 82)',
        managementColorIconUser:'#ff6d6dc4',
        managementColorTitleUser:'#ec4343',
        managementColorInputSearch:'#ffffff',
        managementColorCardBackground: '#fff7f7', 
        managementColorBorderInput: '#ffc2c2',
        managementOnlineStatus: '#1a9c1a',
        managementFieldsBorder: '#d1d1d1',
        managementColorBackgroundDisabled: '#f8f8f8',
        managementColorBorderDisabled: '#e0e0e0',
        managementColorTextDisabled: '#999999',
        managementColorBadgeBackground: '#ec4343',

        // Centro de alertas: superficies neutras y acento funcional
        alertsColorCanvas: '#f5f6f8',
        alertsColorSurface: '#ffffff',
        alertsColorSurfaceMuted: '#f8f9fb',
        alertsColorBorder: '#dde1e7',
        alertsColorBorderStrong: '#c9ced8',
        alertsColorText: '#20242c',
        alertsColorMuted: '#68707d',
        alertsColorAccent: '#b93d3d',
        alertsColorAccentSoft: '#f8eeee',
        alertsColorSuccess: '#257a45',
        alertsColorWarning: '#9a6700',
        alertsColorShadow: 'rgba(15, 23, 42, 0.12)',
        
        // Colores para usuarios compartidos (primario rojo)
        managementSharedUserBackground: '#fefefe',
        managementSharedUserBackgroundEnd: '#fff8f8',
        managementSharedUserBorder: '#ffc2c2',
        managementSharedUserBorderAccent: '#ffd4d4',
        managementSharedUserIconBackground: '#bd3535',
        managementSharedUserIconBackgroundEnd: '#c64444',
        managementSharedUserBadgeBackground: '#bd3535',
        managementSharedUserBadgeBackgroundEnd: '#c64444',
        managementSharedUserTextTitle: '#bd3535',
        managementSharedUserTextSubtitle: '#c64444',
        managementSharedUserTextFooter: '#e26b6b',
        managementSharedUserShadow: 'rgba(189, 53, 53, 0.08)',
        managementSharedUserShadowHover: 'rgba(189, 53, 53, 0.15)',
        managementSharedUserBadgeShadow: 'rgba(189, 53, 53, 0.25)',
        managementSharedUserBadgeShadowPulse: 'rgba(189, 53, 53, 0.4)',
        managementSharedUserShimmer: 'rgba(189, 53, 53, 0.03)',

        // Paleta específica para SMS/chat (light)
        // Fondo general y texto del contenedor (light)
        managementSmsBackground: '#e8eaef',
        managementSmsBorder: '#c9cdd8',
        managementSmsText: '#121622',
        managementSmsIncomingText: '#eef3ff',
        managementSmsMuted: '#4f5668',
        managementSmsStatusDelivered: '#1f8f2f',
        managementSmsStatusPending: '#6b7280',
        // Nubes (usar colores oscuros como en dark)
        managementSmsIncomingBg: '#151924',
        managementSmsIncomingBorder: '#222836',
        managementSmsOutgoingBg: '#2f3c52',
        managementSmsOutgoingBorder: '#263346',
        managementSmsOutgoingText: '#eef3ff'
       
      },
      
      dark: {
         managementColorBackgroundUser:'rgb(33, 33, 33)',
         managementColorTextUser:'rgb(222, 222, 222)',
         managementColorIconUser:'#ff6d6dc4',
         managementColorTitleUser:'#ec4343',
         managementColorInputSearch:'#1f1f1f',
         managementColorCardBackground: '#1f1f1f',
         managementColorBorderInput: '#ff6d6dc4',
         managementOnlineStatus: '#15f915',
         managementFieldsBorder: '#1f1f1f',
         managementColorBackgroundDisabled: '#2a2a2a',
         managementColorBorderDisabled: '#3d3d3d',
         managementColorTextDisabled: '#6c6c6c',
         managementColorBadgeBackground: '#d63838',

         // Centro de alertas: equivalente sobrio para modo oscuro
         alertsColorCanvas: '#151719',
         alertsColorSurface: '#1e2023',
         alertsColorSurfaceMuted: '#25282d',
         alertsColorBorder: '#343840',
         alertsColorBorderStrong: '#474c56',
         alertsColorText: '#f4f4f5',
         alertsColorMuted: '#a5abb5',
         alertsColorAccent: '#ef6b6b',
         alertsColorAccentSoft: 'rgba(239, 107, 107, 0.12)',
         alertsColorSuccess: '#62c486',
         alertsColorWarning: '#e5ad55',
         alertsColorShadow: 'rgba(0, 0, 0, 0.45)',
         
         // Colores para usuarios compartidos (dark theme - primario rojo)
         managementSharedUserBackground: '#2d1818',
         managementSharedUserBackgroundEnd: '#3d2020',
         managementSharedUserBorder: '#cf3f3f',
         managementSharedUserBorderAccent: '#dd4747',
         managementSharedUserIconBackground: '#ff7070',
         managementSharedUserIconBackgroundEnd: '#ff5050',
         managementSharedUserBadgeBackground: '#ff7070',
         managementSharedUserBadgeBackgroundEnd: '#ff5050',
         managementSharedUserTextTitle: '#ff9090',
         managementSharedUserTextSubtitle: '#ff7070',
         managementSharedUserTextFooter: '#e26b6b',
         managementSharedUserShadow: 'rgba(255, 112, 112, 0.12)',
         managementSharedUserShadowHover: 'rgba(255, 112, 112, 0.2)',
         managementSharedUserBadgeShadow: 'rgba(255, 112, 112, 0.3)',
         managementSharedUserBadgeShadowPulse: 'rgba(255, 112, 112, 0.5)',
         managementSharedUserShimmer: 'rgba(255, 112, 112, 0.05)',

         // Paleta específica para SMS/chat (dark)
         managementSmsBackground: '#0f1116',
         managementSmsBorder: '#1c2029',
         managementSmsText: '#e8ecf5',
         managementSmsIncomingText: '#e8ecf5',
         managementSmsMuted: '#8a92a5',
         managementSmsIncomingBg: '#151924',
         managementSmsIncomingBorder: '#222836',
         managementSmsOutgoingBg: '#2f3c52',
         managementSmsOutgoingBorder: '#263346',
         managementSmsOutgoingText: '#eef3ff',
         managementSmsStatusDelivered: '#24c34a',
        managementSmsStatusPending: '#8a92a5'
      }
}
